files:
  - source: /**/main/res/values/strings.xml
    translation: /**/main/res/values-%android_code%/%original_file_name%
  - source: /**/fastlane/metadata/android/en-US/*.txt
    translation: /**/fastlane/metadata/android/%locale%/%original_file_name%
