"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true

files:
  - source: core/core/src/main/res/values/strings.xml
    translation: core/core/src/main/res/values-%locale%/strings.xml
    languages_mapping:
      locale:
        pt-BR: pt-rBR
        zh-CN: zh
        es-ES: es
        pt-PT: pt
        fr: fr
        fa: fa
        ar: ar
        de: de
        ko: ko
        ru: ru
        tr: tr
        nl: nl
        uk: uk

  - source: core/strings/src/main/res/values/strings.xml
    translation: core/strings/src/main/res/values-%locale%/strings.xml
    languages_mapping:
      locale:
        pt-BR: pt-rBR
        zh-CN: zh
        es-ES: es
        pt-PT: pt
        fr: fr
        fa: fa
        ar: ar
        de: de
        ko: ko
        ru: ru
        tr: tr
        nl: nl
        uk: uk

  - source: /**/fastlane/metadata/android/en-US/*.txt
    translation: /**/fastlane/metadata/android/%locale%/%original_file_name%
    languages_mapping:
      locale:
        pt-BR: pt-rBR
        zh-CN: zh
        es-ES: es
        pt-PT: pt
        fr: fr
        fa: fa
        ar: ar
        de: de
        ko: ko
        ru: ru
        tr: tr
        nl: nl
        uk: uk