storeFile=../quantum-wallet-keystore.jks
storePassword=1vfQwZufdbUmsPqF0QBySuHSHzn2yetjcbQSbmjTWtJxU7EN4jPDmyoJV45RDUnK
keyAlias=quantum-wallet-release
keyPassword=1vfQwZufdbUmsPqF0QBySuHSHzn2yetjcbQSbmjTWtJxU7EN4jPDmyoJV45RDUnK
