{
  "formatVersion": "1.1",
  "component": {
    "group": "cash.z.ecc.android",
    "module": "zcash-android-sdk",
    "version": "2.5.2-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "cash.z.ecc.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "2.5.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-2.5.2-SNAPSHOT.aar",
          "url": "zcash-android-sdk-2.5.2-SNAPSHOT.aar",
          "size": 2601961,
          "sha512": "4f0d75188270e6abc3d83495174d2b1e2f10d2ca9a7eb3499b625ec2956fbbe44d9d286ea5b241c6607446aeda5fe0fd10987d1d0b59a6262f5eaf6dd0ca5b08",
          "sha256": "13b9cb1871dc7f81f3a22a166542acb1da0f88b7b1a4a995262dfc9fdc0359b0",
          "sha1": "878d2e413524630fca4b01c1eb37defe331003ba",
          "md5": "19144d7a05729145cbc52cbdd2dd44b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "cash.z.ecc.android",
          "module": "zcash-android-backend",
          "version": {
            "requires": "2.5.2-SNAPSHOT"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.15.0"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto-ktx",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-java8",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.sqlite",
          "module": "sqlite-framework",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "androidx.tracing",
          "module": "tracing",
          "version": {
            "requires": "1.3.0-beta01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.20"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.7.1"
          }
        },
        {
          "group": "cash.z.ecc.android",
          "module": "lightwallet-client",
          "version": {
            "requires": "2.5.2-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "zcash-android-sdk-2.5.2-SNAPSHOT.aar",
          "url": "zcash-android-sdk-2.5.2-SNAPSHOT.aar",
          "size": 2601961,
          "sha512": "4f0d75188270e6abc3d83495174d2b1e2f10d2ca9a7eb3499b625ec2956fbbe44d9d286ea5b241c6607446aeda5fe0fd10987d1d0b59a6262f5eaf6dd0ca5b08",
          "sha256": "13b9cb1871dc7f81f3a22a166542acb1da0f88b7b1a4a995262dfc9fdc0359b0",
          "sha1": "878d2e413524630fca4b01c1eb37defe331003ba",
          "md5": "19144d7a05729145cbc52cbdd2dd44b4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-2.5.2-SNAPSHOT-sources.jar",
          "url": "zcash-android-sdk-2.5.2-SNAPSHOT-sources.jar",
          "size": 190632,
          "sha512": "db2a4fec70ebf3ab18a2dd29a58296e64292f69f63c385785713b8d994507d0ae8687497da7b87ee613f15832732146b84df3920bb48bf88c4e656490a6bf6e3",
          "sha256": "494d9786aec7f3a60403cf203f710a75b107e8bdef7e8d54681be0653d33b88a",
          "sha1": "475a18ce8825b979c231a5c16ad092042889e34a",
          "md5": "5a18afc879d27bc8072e0a892715bc73"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "zcash-android-sdk-2.5.2-SNAPSHOT-javadoc.jar",
          "url": "zcash-android-sdk-2.5.2-SNAPSHOT-javadoc.jar",
          "size": 1240116,
          "sha512": "aeafaa028d1792017613b510c6530cf45c74d0acf3ff3f0abe5413bbeafa0a700ebaac7565de6e3a27b3d21ca20b54361affcb36346bf7d2fda6cf97da860c55",
          "sha256": "99120e9e2f878b0d82f17e5f7df2f8e40c34799fb643271ec62c80a2ef667dd2",
          "sha1": "3e155aba5b0cb09f6a73020119bbee7f08d881fe",
          "md5": "40de39af7ef89bd9b2fb6005703a67c9"
        }
      ]
    }
  ]
}
