default_platform(:android)

platform :android do
  before_all do
    reset_git_repo(force: true, skip_clean: true)
  end

  desc "Submit a new Version Build"
  lane :dev_build do |options|
    commit = last_git_commit
    build_number = options[:build_number]

    gradle(task: "clean")
    gradle(task: "assembleDevMainnetVersionDebug", flags: "--stacktrace --no-daemon")

    upload_to_hockey(notes: "Author: #{commit[:author]}, changes: #{commit[:message]}")
  end

  desc "Submit a new Master Build"
  lane :dev_testnet_build do |options|
    commit = last_git_commit
    build_number = options[:build_number]

    gradle(task: "clean")
    gradle(task: "assembleDevMainnetMasterDebug", flags: "--stacktrace --no-daemon")

    upload_to_hockey(notes: "Author: #{commit[:author]}, changes: #{commit[:message]}")
  end

  private_lane :upload_to_hockey do |options|
      hockey(
        api_token: "61f67135578645d3a9a762baa0a75a13",
        notes: options[:notes],
      )
  end

end
