package cash.p.terminal.entities.transactionrecords

enum class TransactionRecordType {
    UNKNOWN,

    TON,

    SOLANA_INCOMING,
    SOLANA_OUTGOING,
    SOLANA_UNKNOWN,

    BITCOIN_INCOMING,
    BITCOIN_OUTGOING,

    EVM,
    EVM_APPROVE,
    EVM_CONTRACT_CALL,
    EVM_CONTRACT_CREATION,
    EVM_INCOMING,
    EVM_OUTGOING,
    EVM_EXTERNAL_CONTRACT_CALL,
    EVM_SWAP,
    EVM_UNKNOWN_SWAP,

    TRON,
    TRON_APPROVE,
    TRON_CONTRACT_CALL,
    TRON_EXTERNAL_CONTRACT_CALL,
    TRON_INCOMING,
    TRON_OUTGOING,

    MONERO_INCOMING,
    MONERO_OUTGOING,
}
