name: Android CI (release)

on:
  push:
    branches: [ master, test ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hsdao/android-release-build:java-17-update

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Build Number
        env:
          APPCENTER_NUMBER: 147
        run: |
          echo "BUILD_NUMBER_NEW=$(($APPCENTER_NUMBER+$GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Get Release Notes
        id: notes
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          echo "val=Author: $AUTHOR, changes: $MESSAGE" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build CI Release
        run: ./gradlew clean assembleCiRelease --stacktrace --no-daemon
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER_NEW }}

      - name: Upload CI Release to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:308085819273:android:d1451c165f07056ea00358
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          groups: horsysteam
          file: app/build/outputs/apk/ci/release/app-ci-release.apk
          releaseNotes: ${{ steps.notes.outputs.val }}
