name: Android CI (Dev)

on:
  push:
    branches: [ version/* ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set Build Number
        env:
          APPCENTER_NUMBER: 1210
        run: |
          echo "BUILD_NUMBER_NEW=$(($APPCENTER_NUMBER+$GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Get Release Notes
        id: notes
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          MESSAGE=$(git log -1 --pretty=format:'%s')
          echo "val=Author: $AUTHOR, changes: $MESSAGE" >> $GITHUB_OUTPUT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build CI Debug
        run: ./gradlew clean assembleCiDebug --stacktrace --no-daemon
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER_NEW }}

      - name: Upload CI Debug to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:308085819273:android:1b039e927925b879a00358
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          groups: horsysteam
          file: app/build/outputs/apk/ci/debug/app-ci-debug.apk
          releaseNotes: ${{ steps.notes.outputs.val }}

      - name: Build F-Droid CI Debug
        run: ./gradlew clean assembleFdroidCiDebug --stacktrace --no-daemon
        env:
          BUILD_NUMBER: ${{ env.BUILD_NUMBER_NEW }}

      - name: Upload F-Droid CI Debug to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:308085819273:android:3c060bb15aa35d79a00358
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
          groups: horsysteam
          file: app/build/outputs/apk/fdroidCi/debug/app-fdroidCi-debug.apk
          releaseNotes: "F-Droid Build - ${{ steps.notes.outputs.val }}"
